### ISSUE TITLE
localization and inference details

### ISSUE THREAD

**Issue by ChethanN01** [tomas-gajarsky/facetorch#43]
Team,

i would like to know this model can be inference on video?

thanks
Chethan

**Comment by tomas-gajarsky** [comment]
Hello Chethan,

Indeed, it is possible to use facetorch for video processing, given that videos are essentially sequences of images. However, please note that you'll need to first extract the frames from your video file, as FaceAnalyzer currently lacks built-in support for direct video file processing.

To provide more specific guidance, it would be helpful if you could share additional information. In particular, could you clarify which model you are intending to use? Furthermore, are you considering real-time video processing, or is this for pre-recorded video files?

Understanding these details will allow me to give you more targeted advice. Please feel free to reach out if you need further assistance or clarification.

**Comment by ChethanN01** [comment]
thanks for details, i am doing processing on prerecorded videos. i have done the inference and stich back the images.

i would like to do instead if  class it i would like to change to class name. am working on how best i can do with this.

**Comment by ChethanN01** [comment]
i am using facetorch to get emotion details

**Comment by tomas-gajarsky** [comment]
> i would like to do instead if class it i would like to change to class name. am working on how best i can do with this.

Your question is a bit unclear to me, but if I'm understanding you correctly, you'd like to use class names instead of class identifiers in your processing. If that's the case, the FaceAnalyzer should return class names as part of its response, which you should be able to utilize in your application. If this isn't what you were asking or you need further clarification, please provide a bit more context or detail so I can assist you better.
