### ISSUE TITLE
Image normalization 

### ISSUE THREAD

**Issue by Vuillecard** [tomas-gajarsky/facetorch#73]
Hello, 

Thank you for this project. It is very helpful. It seems to have a discrepancy in the normalization of the image. I noticed two potential issues:

1. The detector retinaNnet applies some normalization which also affects the face crop data.face. Then, the normalization order should stay the same in the unifier to denormalize the face crop into [0,1]. Right now the face crop can have a negative value.
2. The image is loaded with torchvision resulting in RGB images. From the RetinaNet implementation preprocessing the image is loaded in BGR format the mean they applied is (104, 117, 123). In facetorch, the transform is applied before rgbtobgr() thus I think that the correct order would be (123,117,104).

With the modification of point 1, all face crops are in [0,1]. For point 2 it is harder to check

**Comment by tomas-gajarsky** [comment]
Thank you for the detailed feedback! You were spot on - the issue was with the order of the color channel means in the RetinaFace detector preprocessor. Updating the means to (123, 117, 104) fixed both the color normalization and the face crop normalization range.

This is addressed in version 0.5.1. Let me know if you notice anything else!
